2026-02-27T14:43:34.888Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:43:34.889Z [console][error] Failed to fetch results {}
2026-02-27T14:43:35.321Z [console][warn] Failed to fetch events from Soroban RPC {"code":-32602,"message":"startLedger must be positive"}
2026-02-27T14:43:42.275Z [console][error] Connection failed {}
2026-02-27T14:44:12.540Z [console][warn] Attempting to handle text change for non-editing element
2026-02-27T14:43:35.543Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":117,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":96,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  94 |\n  95 |   useEffect(() => {\n> 96 |     fetchResults();\n     |     ^\n  97 |     fetchEvents();\n  98 |\n  99 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:43:43.049Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"handleVote","arguments":[],"lineNumber":401,"column":19},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"onClick","arguments":[],"lineNumber":626,"column":54},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484162 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484163 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484164 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batc... [truncated]
2026-02-27T14:43:47.758Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"Button","arguments":[],"lineNumber":337,"column":229},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"WalletButton","arguments":[],"lineNumber":1142,"column":229},{"file":"file:///home/user/app/.next/static/ch... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484182 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batchedUpdates$1"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":7,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16705,"methodName":"dispatchEventForPluginEventSystem"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":11,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":... [truncated]
2026-02-27T14:43:50.624Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:43:52.274Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"Button","arguments":[],"lineNumber":337,"column":229},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"WalletButton","arguments":[],"lineNumber":1142,"column":229},{"file":"file:///home/user/app/.next/static/ch... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484198 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batchedUpdates$1"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":7,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16705,"methodName":"dispatchEventForPluginEventSystem"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":11,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":... [truncated]
2026-02-27T14:44:05.575Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:44:16.122Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"handleVote","arguments":[],"lineNumber":401,"column":19},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"onClick","arguments":[],"lineNumber":626,"column":54},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484218 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484220 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484219 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batc... [truncated]
2026-02-27T14:44:20.229Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"Button","arguments":[],"lineNumber":337,"column":229},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"WalletButton","arguments":[],"lineNumber":1142,"column":229},{"file":"file:///home/user/app/.next/static/ch... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484236 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batchedUpdates$1"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":7,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16705,"methodName":"dispatchEventForPluginEventSystem"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":11,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":... [truncated]
2026-02-27T14:44:20.671Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:44:35.508Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:44:50.670Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:45:06.237Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:45:21.105Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:45:36.223Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}}]
2026-02-27T14:46:45.512Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:46:45.534Z [console][error] Failed to fetch results {}
2026-02-27T14:46:46.219Z [console][warn] Failed to fetch events from Soroban RPC {"code":-32602,"message":"filter 1 invalid: contract ID 1 invalid"}
2026-02-27T14:46:46.506Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":122,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":103,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  101 |\n  102 |   useEffect(() => {\n> 103 |     fetchResults();\n      |     ^\n  104 |     fetchEvents();\n  105 |\n  106 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:46:54.493Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useEffect","arguments":[],"lineNumber":148,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:47:10.168Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}}]
2026-02-27T14:46:45.534Z [console][error] Failed to fetch results {}
2026-02-27T14:46:46.219Z [console][warn] Failed to fetch events from Soroban RPC {"code":-32602,"message":"filter 1 invalid: contract ID 1 invalid"}
2026-02-27T14:47:41.012Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:47:41.025Z [console][error] Failed to fetch results {}
2026-02-27T14:47:42.167Z [console][warn] Failed to fetch events from Soroban RPC {"code":-32602,"message":"filter 1 invalid: contract ID 1 invalid"}
2026-02-27T14:46:46.506Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":34,"column":231},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":122,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":29,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  27 |       \n  28 |       const contractAddress = CONTRACT_ID;\n> 29 |       const txBuilder = new SorobanRpc.Server(STELLAR_NETWORK.rpcUrl); // Using server directly for read-only simulation if needed\n     |                                        ^\n  30 |       \n  31 |       // Since it's a read-only call, we simulate the invocation\n  32 |       // This is a placeholder for actual simulation logic in a complex ScVal environment"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":103,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  101 |\n  102 |   useEffect(() => {\n> 103 |     fetchResults();\n      |     ^\n  104 |     fetchEvents();\n  105 |\n  106 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:46:54.493Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useEffect","arguments":[],"lineNumber":148,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:47:10.168Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}}]
2026-02-27T14:47:25.088Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}}]
2026-02-27T14:47:42.056Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:47:41.025Z [console][error] Failed to fetch results {}
2026-02-27T14:47:42.167Z [console][warn] Failed to fetch events from Soroban RPC {"code":-32602,"message":"filter 1 invalid: contract ID 1 invalid"}
2026-02-27T14:47:58.979Z [console][error] Connection failed {}
2026-02-27T14:48:10.448Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:48:10.449Z [console][error] Failed to fetch results {}
2026-02-27T14:47:25.088Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":33,"column":63}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}}]
2026-02-27T14:47:42.056Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:47:56.930Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}}]
2026-02-27T14:47:59.643Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"Button","arguments":[],"lineNumber":370,"column":229},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"WalletButton","arguments":[],"lineNumber":1172,"column":229},{"file":"file:///home/user/app/.next/static/ch... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484506 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batchedUpdates$1"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":7,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16705,"methodName":"dispatchEventForPluginEventSystem"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":11,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":... [truncated]
2026-02-27T14:48:11.365Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:48:10.448Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:48:10.449Z [console][error] Failed to fetch results {}
2026-02-27T14:48:12.498Z [console][error] Connection failed {}
2026-02-27T14:48:23.059Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:48:23.062Z [console][error] Failed to fetch results {}
2026-02-27T14:48:11.365Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:48:13.731Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"handleVote","arguments":[],"lineNumber":434,"column":19},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"onClick","arguments":[],"lineNumber":656,"column":54},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484610 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484611 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484612 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batc... [truncated]
2026-02-27T14:48:16.245Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_9a05686c._.js","methodName":"StellarProvider.useCallback[connect]","arguments":[],"lineNumber":2124,"column":60},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"executeDispatch","arguments":[],"lineNumber":10906,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"runWithFiberInDEV","arguments":[],"lineNumber":3073,"column":74},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"processDispatchQueue","arguments":[],"lineNumber":10932,"column":41},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"<unknown>","arguments":[],"lineNumber":11223,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"batchedUpdates$1","arguments":[],"lineNumber":4384,"column":44},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEventForPluginEventSystem","arguments":[],"lineNumber":11008,"column":9},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchEvent","arguments":[],"lineNumber":13121,"column":37},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_compiled_19d9bb24._.js","methodName":"dispatchDiscreteEvent","arguments":[],"lineNumber":13103,"column":64},{"file":"<anonymous>","methodName":"button","arguments":[],"lineNumber":null,"column":null},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"Button","arguments":[],"lineNumber":370,"column":229},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"WalletButton","arguments":[],"lineNumber":1172,"column":229},{"file":"file:///home/user/app/.next/static/ch... [truncated]
  response: [{"status":"rejected","reason":"[Error: Original file () outside project (file:///home/)\n\nDebug info:\n- Execution of TaskId { id: 2147484628 } transient failed\n- Original file () outside project (file:///home/)] {\n  code: 'GenericFailure'\n}"},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16501,"methodName":"executeDispatch"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":30,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":844,"methodName":"runWithFiberInDEV"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":19,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16551,"methodName":"processDispatchQueue"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":9,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":17149,"methodName":"<unknown>"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":40,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":3262,"methodName":"batchedUpdates$1"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":7,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":true,"lineNumber":16705,"methodName":"dispatchEventForPluginEventSystem"},"originalCodeFrame":null}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":11,"file":"node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js","ignored":... [truncated]
2026-02-27T14:48:23.829Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":35,"column":63},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":15,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":32,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  30 |         // Using a more direct approach to simulate a contract call\n  31 |         const sim = await rpc.simulateTransaction(\n> 32 |           new TransactionBuilder(\n     |               ^\n  33 |             new Horizon.Account(\"GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF\", \"0\"),\n  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation("}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:48:31.554Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":36,"column":224},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js?id=%255Bproject%255D%252Fuser%252Fapp%252Fsrc%252Fhooks%252FusePoll.ts+%255Bapp-client%255D+%2528ecmascript%2529","methodName":"usePoll.useEffect","arguments":[],"lineNumber":148,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":23,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":36,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation(\n> 36 |             Operation.invokeContract({\n     |                       ^\n  37 |               contractId: CONTRACT_ID,\n  38 |               function: \"get_results\",\n  39 |               args: [xdr.ScVal.scvU32(POLL_ID)],"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
2026-02-27T14:58:25.828Z [console][error] A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch 

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        data-orchids-id="src/app/layout.tsx:20:4"
                        data-orchids-name="html"
                        lang="en"
-                       style={{--swk-background:"#fcfcfcff",--swk-background-secondary:"#f8f8f8ff",--swk-foreground-strong:"#0...", ...}}
                      >
                    ...
        ...

2026-02-27T14:58:25.830Z [console][error] Failed to fetch results {}
2026-02-27T14:58:27.049Z [network][POST 200] /__nextjs_original-stack-frames
  request: {"frames":[{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useCallback[fetchResults]","arguments":[],"lineNumber":38,"column":224},{"file":"file:///home/user/app/.next/static/chunks/user_app_src_b537ba82._.js","methodName":"usePoll.useEffect","arguments":[],"lineNumber":150,"column":13},{"file":"file:///home/user/app/.next/static/chunks/45749_next_dist_69ef9e6f._.js","methodName":"ClientPageRoot","arguments":[],"lineNumber":2061,"column":50}],"isServer":false,"isEdgeServer":false,"isAppDirectory":true}
  response: [{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":23,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":36,"methodName":"usePoll.useCallback[fetchResults]"},"originalCodeFrame":"  34 |             { fee: \"100\", networkPassphrase: STELLAR_NETWORK.passphrase }\n  35 |           ).addOperation(\n> 36 |             Operation.invokeContract({\n     |                       ^\n  37 |               contractId: CONTRACT_ID,\n  38 |               function: \"get_results\",\n  39 |               args: [xdr.ScVal.scvU32(POLL_ID)],"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":5,"file":"src/hooks/usePoll.ts","ignored":false,"lineNumber":127,"methodName":"usePoll.useEffect"},"originalCodeFrame":"  125 |\n  126 |   useEffect(() => {\n> 127 |     fetchResults();\n      |     ^\n  128 |     fetchEvents();\n  129 |\n  130 |     const resultInterval = setInterval(fetchResults, 15000);"}},{"status":"fulfilled","value":{"originalStackFrame":{"arguments":[],"column":12,"file":"node_modules/next/src/client/components/client-page.tsx","ignored":true,"lineNumber":60,"methodName":"ClientPageRoot"},"originalCodeFrame":null}}]
